// Place any global data in this file.
// You can import this data from anywhere in your site by using the `import` keyword.

export const SITE_TITLE = 'Espai.ai';
export const SITE_DESCRIPTION = 'AI-powered business process optimization';

export const LANGUAGES = {
  en: 'English',
  es: 'Español', 
  ca: 'Català',
  de: 'Deutsch'
};

export const DEFAULT_LANG = 'en';

export const UI_TEXT = {
  en: {
    'site.title': 'Espai.ai',
    'site.description': 'AI-powered business process optimization',
    // SEO Meta Descriptions
    'meta.home.description': 'Stop wasting time on repetitive tasks. Espai.ai records your processes, finds inefficiencies with AI, and creates automations that save 20+ hours per week. Pay only when you start saving.',
    'meta.about.description': 'Espai.ai helps businesses eliminate manual work through intelligent process automation. We\'ve helped companies save 40% of employee time and reduce operational costs by 30%.',
    'meta.pricing.description': 'Transparent pricing: €70-100 per device per month. You pay only after automations start saving you time. Most companies see ROI within 30 days.',
    'meta.faq.description': 'Get answers about Espai.ai\'s AI automation platform. Learn how our process recording and analysis can save your business 20+ hours per week.',
    'meta.contact.description': 'Ready to save 20+ hours per week? Contact Espai.ai for a free process analysis. See how AI automation can transform your business operations.',
    'meta.privacy.description': 'Espai.ai privacy policy and data protection practices. Learn how we secure your business data in our AI process automation platform.',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.pricing': 'Pricing',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.resources': 'Resources',
    'nav.privacy': 'Privacy Policy',
    'hero.title': 'Save 20+ Hours Per Week with AI Automation',
    'hero.subtitle': 'Stop wasting time on repetitive tasks. Our AI records your processes, finds inefficiencies, and creates automations that actually work.',
    'hero.cta': 'Start Free Analysis',
    'hero.cta.secondary': 'See How It Works',
    'footer.rights': 'All rights reserved.',
    'footer.crafted': 'crafted with ♡ in barcelona',
    // Contact form translations
    'contact.title': 'Get Your Free Process Analysis',
    'contact.subtitle': 'See how much time your business can save with AI automation',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.company': 'Company Name',
    'contact.form.phone': 'Phone Number',
    'contact.form.employees': 'Number of Employees',
    'contact.form.employees.option1': '1-10 employees',
    'contact.form.employees.option2': '11-50 employees',
    'contact.form.employees.option3': '51-200 employees',
    'contact.form.employees.option4': '200+ employees',
    'contact.form.interest': 'I\'m interested in',
    'contact.form.interest.demo': 'Free Process Analysis',
    'contact.form.interest.pricing': 'Pricing Information',
    'contact.form.interest.other': 'Other',
    'contact.form.message': 'Tell us about your current processes and pain points',
    'contact.form.submit': 'Get Free Analysis',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully! We\'ll contact you within 24 hours to schedule your free analysis.',
    'contact.form.error': 'Error sending message. Please try again or contact us directly.',
    'contact.form.required': 'This field is required',
    // Language detection translations
    'lang.detection.title': 'Language Preference',
    'lang.detection.message': 'We detected your browser language is {language}. Would you like to switch to this language?',
    'lang.detection.switch': 'Switch to {language}',
    'lang.detection.stay': 'Stay in English',
    'lang.detection.dismiss': 'Don\'t ask again'
  },
  es: {
    'site.title': 'Espai.ai',
    'site.description': 'Optimización de procesos empresariales con IA',
    // SEO Meta Descriptions
    'meta.home.description': 'Deja de perder tiempo en tareas repetitivas. Espai.ai registra tus procesos, encuentra ineficiencias con IA y crea automatizaciones que ahorran 20+ horas por semana. Paga solo cuando empieces a ahorrar.',
    'meta.about.description': 'Espai.ai ayuda a las empresas a eliminar el trabajo manual mediante automatización inteligente de procesos. Hemos ayudado a empresas a ahorrar 40% del tiempo de empleados y reducir costos operativos en 30%.',
    'meta.pricing.description': 'Precios transparentes: €70-100 por dispositivo por mes. Pagas solo después de que las automatizaciones empiecen a ahorrarte tiempo. La mayoría de empresas ven ROI en 30 días.',
    'meta.faq.description': 'Obtén respuestas sobre la plataforma de automatización IA de Espai.ai. Aprende cómo nuestro registro y análisis de procesos puede ahorrarle a tu empresa 20+ horas por semana.',
    'meta.contact.description': '¿Listo para ahorrar 20+ horas por semana? Contacta Espai.ai para un análisis gratuito de procesos. Ve cómo la automatización IA puede transformar tus operaciones.',
    'meta.privacy.description': 'Política de privacidad y prácticas de protección de datos de Espai.ai. Aprende cómo protegemos tus datos de negocio en nuestra plataforma de automatización de procesos con IA.',
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.pricing': 'Precios',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contacto',
    'nav.resources': 'Recursos',
    'nav.privacy': 'Política de Privacidad',
    'hero.title': 'Ahorra 20+ Horas Por Semana con Automatización IA',
    'hero.subtitle': 'Deja de perder tiempo en tareas repetitivas. Nuestra IA registra tus procesos, encuentra ineficiencias y crea automatizaciones que realmente funcionan.',
    'hero.cta': 'Análisis Gratuito',
    'hero.cta.secondary': 'Ver Cómo Funciona',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.crafted': 'creado con ♡ en barcelona',
    // Contact form translations
    'contact.title': 'Obtén Tu Análisis Gratuito de Procesos',
    'contact.subtitle': 'Ve cuánto tiempo puede ahorrar tu empresa con automatización IA',
    'contact.form.name': 'Nombre Completo',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.company': 'Nombre de la Empresa',
    'contact.form.phone': 'Número de Teléfono',
    'contact.form.employees': 'Número de Empleados',
    'contact.form.employees.option1': '1-10 empleados',
    'contact.form.employees.option2': '11-50 empleados',
    'contact.form.employees.option3': '51-200 empleados',
    'contact.form.employees.option4': '200+ empleados',
    'contact.form.interest': 'Estoy interesado en',
    'contact.form.interest.demo': 'Análisis Gratuito de Procesos',
    'contact.form.interest.pricing': 'Información de Precios',
    'contact.form.interest.other': 'Otro',
    'contact.form.message': 'Cuéntanos sobre tus procesos actuales y problemas',
    'contact.form.submit': 'Obtener Análisis Gratuito',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': '¡Mensaje enviado con éxito! Te contactaremos en 24 horas para programar tu análisis gratuito.',
    'contact.form.error': 'Error al enviar el mensaje. Por favor intenta de nuevo o contáctanos directamente.',
    'contact.form.required': 'Este campo es obligatorio',
    // Language detection translations
    'lang.detection.title': 'Preferencia de Idioma',
    'lang.detection.message': 'Detectamos que tu navegador está en {language}. ¿Te gustaría cambiar a este idioma?',
    'lang.detection.switch': 'Cambiar a {language}',
    'lang.detection.stay': 'Quedarse en Inglés',
    'lang.detection.dismiss': 'No preguntar de nuevo'
  },
  ca: {
    'site.title': 'Espai.ai',
    'site.description': 'Optimització de processos empresarials amb IA',
    // SEO Meta Descriptions
    'meta.home.description': 'Deixa de perdre temps en tasques repetitives. Espai.ai registra els teus processos, troba ineficiències amb IA i crea automatitzacions que estalvien 20+ hores per setmana. Paga només quan comences a estalviar.',
    'meta.about.description': 'Espai.ai ajuda les empreses a eliminar el treball manual mitjançant automatització intel·ligent de processos. Hem ajudat empreses a estalviar 40% del temps d\'empleats i reduir costos operatius en 30%.',
    'meta.pricing.description': 'Preus transparents: €70-100 per dispositiu per mes. Pagues només després que les automatitzacions comencin a estalviar-te temps. La majoria d\'empreses veuen ROI en 30 dies.',
    'meta.faq.description': 'Obtén respostes sobre la plataforma d\'automatització IA d\'Espai.ai. Aprèn com el nostre registre i anàlisi de processos pot estalviar a la teva empresa 20+ hores per setmana.',
    'meta.contact.description': 'Preparat per estalviar 20+ hores per setmana? Contacta Espai.ai per una anàlisi gratuïta de processos. Veu com l\'automatització IA pot transformar les teves operacions.',
    'meta.privacy.description': 'Política de privacitat i pràctiques de protecció de dades d\'Espai.ai. Aprèn com protegim les teves dades de negoci a la nostra plataforma d\'automatització de processos amb IA.',
    'nav.home': 'Inici',
    'nav.about': 'Sobre nosaltres',
    'nav.pricing': 'Preus',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contacte',
    'nav.resources': 'Recursos',
    'nav.privacy': 'Política de Privacitat',
    'hero.title': 'Estalvia 20+ Hores Per Setmana amb Automatització IA',
    'hero.subtitle': 'Deixa de perdre temps en tasques repetitives. La nostra IA registra els teus processos, troba ineficiències i crea automatitzacions que realment funcionen.',
    'hero.cta': 'Anàlisi Gratuïta',
    'hero.cta.secondary': 'Veure Com Funciona',
    'footer.rights': 'Tots els drets reservats.',
    'footer.crafted': 'fet amb ♡ a barcelona',
    // Contact form translations
    'contact.title': 'Obtén La Teva Anàlisi Gratuïta de Processos',
    'contact.subtitle': 'Veus quant temps pot estalviar la teva empresa amb automatització IA',
    'contact.form.name': 'Nom Complet',
    'contact.form.email': 'Correu Electrònic',
    'contact.form.company': 'Nom de l\'Empresa',
    'contact.form.phone': 'Número de Telèfon',
    'contact.form.employees': 'Número d\'Empleats',
    'contact.form.employees.option1': '1-10 empleats',
    'contact.form.employees.option2': '11-50 empleats',
    'contact.form.employees.option3': '51-200 empleats',
    'contact.form.employees.option4': '200+ empleats',
    'contact.form.interest': 'Estic interessat en',
    'contact.form.interest.demo': 'Anàlisi Gratuïta de Processos',
    'contact.form.interest.pricing': 'Informació de Preus',
    'contact.form.interest.other': 'Altre',
    'contact.form.message': 'Explica\'ns sobre els teus processos actuals i problemes',
    'contact.form.submit': 'Obtener Anàlisi Gratuïta',
    'contact.form.sending': 'Enviant...',
    'contact.form.success': 'Missatge enviat amb èxit! Et contactarem en 24 hores per programar la teva anàlisi gratuïta.',
    'contact.form.error': 'Error en enviar el missatge. Si us plau intenta de nou o contacta\'ns directament.',
    'contact.form.required': 'Aquest camp és obligatori',
    // Language detection translations
    'lang.detection.title': 'Preferència d\'Idioma',
    'lang.detection.message': 'Hem detectat que el teu navegador està en {language}. Vols canviar a aquest idioma?',
    'lang.detection.switch': 'Canviar a {language}',
    'lang.detection.stay': 'Quedar-se en Anglès',
    'lang.detection.dismiss': 'No tornar a preguntar'
  },
  de: {
    'site.title': 'Espai.ai',
    'site.description': 'KI-gestützte Optimierung von Geschäftsprozessen',
    // SEO Meta Descriptions
    'meta.home.description': 'Hören Sie auf, Zeit mit wiederholenden Aufgaben zu verschwenden. Espai.ai zeichnet Ihre Prozesse auf, findet Ineffizienzen mit KI und erstellt Automatisierungen, die 20+ Stunden pro Woche sparen. Zahlen Sie nur, wenn Sie anfangen zu sparen.',
    'meta.about.description': 'Espai.ai hilft Unternehmen dabei, manuelle Arbeit durch intelligente Prozessautomatisierung zu eliminieren. Wir haben Unternehmen geholfen, 40% der Mitarbeiterzeit zu sparen und Betriebskosten um 30% zu reduzieren.',
    'meta.pricing.description': 'Transparente Preise: €70-100 pro Gerät pro Monat. Sie zahlen nur, nachdem Automatisierungen anfangen, Ihnen Zeit zu sparen. Die meisten Unternehmen sehen ROI innerhalb von 30 Tagen.',
    'meta.faq.description': 'Erhalten Sie Antworten zur KI-Automatisierungsplattform von Espai.ai. Erfahren Sie, wie unsere Prozessaufzeichnung und -analyse Ihrem Unternehmen 20+ Stunden pro Woche sparen kann.',
    'meta.contact.description': 'Bereit, 20+ Stunden pro Woche zu sparen? Kontaktieren Sie Espai.ai für eine kostenlose Prozessanalyse. Sehen Sie, wie KI-Automatisierung Ihre Geschäftsabläufe transformieren kann.',
    'meta.privacy.description': 'Datenschutzerklärung und Datenschutzpraxis von Espai.ai. Erfahren Sie, wie wir Ihre Geschäftedaten in unserer KI-Prozessautomatisierungsplattform sichern.',
    'nav.home': 'Startseite',
    'nav.about': 'Über uns',
    'nav.pricing': 'Preise',
    'nav.faq': 'FAQ',
    'nav.contact': 'Kontakt',
    'nav.resources': 'Ressourcen',
    'nav.privacy': 'Datenschutzerklärung',
    'hero.title': 'Sparen Sie 20+ Stunden pro Woche mit KI-Automatisierung',
    'hero.subtitle': 'Hören Sie auf, Zeit mit wiederholenden Aufgaben zu verschwenden. Unsere KI zeichnet Ihre Prozesse auf, findet Ineffizienzen und erstellt Automatisierungen, die wirklich funktionieren.',
    'hero.cta': 'Kostenlose Analyse starten',
    'hero.cta.secondary': 'So funktioniert es',
    'footer.rights': 'Alle Rechte vorbehalten.',
    'footer.crafted': 'gemacht mit ♡ in barcelona',
    // Contact form translations
    'contact.title': 'Erhalten Sie Ihre kostenlose Prozessanalyse',
    'contact.subtitle': 'Sehen Sie, wie viel Zeit Ihr Unternehmen mit KI-Automatisierung sparen kann',
    'contact.form.name': 'Vollständiger Name',
    'contact.form.email': 'E-Mail-Adresse',
    'contact.form.company': 'Firmenname',
    'contact.form.phone': 'Telefonnummer',
    'contact.form.employees': 'Anzahl der Mitarbeiter',
    'contact.form.employees.option1': '1-10 Mitarbeiter',
    'contact.form.employees.option2': '11-50 Mitarbeiter',
    'contact.form.employees.option3': '51-200 Mitarbeiter',
    'contact.form.employees.option4': '200+ Mitarbeiter',
    'contact.form.interest': 'Ich bin interessiert an',
    'contact.form.interest.demo': 'Kostenlose Prozessanalyse',
    'contact.form.interest.pricing': 'Preisinformationen',
    'contact.form.interest.other': 'Andere',
    'contact.form.message': 'Erzählen Sie uns von Ihren aktuellen Prozessen und Problemen',
    'contact.form.submit': 'Kostenlose Analyse erhalten',
    'contact.form.sending': 'Wird gesendet...',
    'contact.form.success': 'Nachricht erfolgreich gesendet! Wir werden uns innerhalb von 24 Stunden bei Ihnen melden, um Ihre kostenlose Analyse zu planen.',
    'contact.form.error': 'Fehler beim Senden der Nachricht. Bitte versuchen Sie es erneut oder kontaktieren Sie uns direkt.',
    'contact.form.required': 'Dieses Feld ist erforderlich',
    // Language detection translations
    'lang.detection.title': 'Spracheinstellung',
    'lang.detection.message': 'Wir haben erkannt, dass Ihr Browser auf {language} eingestellt ist. Möchten Sie zu dieser Sprache wechseln?',
    'lang.detection.switch': 'Zu {language} wechseln',
    'lang.detection.stay': 'Bei Englisch bleiben',
    'lang.detection.dismiss': 'Nicht mehr fragen'
  }
};
