// Place any global data in this file.
// You can import this data from anywhere in your site by using the `import` keyword.

export const SITE_TITLE = 'Espai.ai';
export const SITE_DESCRIPTION = 'AI-powered business process optimization';

export const LANGUAGES = {
  en: 'English',
  es: 'Español', 
  ca: 'Català',
  de: 'Deutsch'
};

export const DEFAULT_LANG = 'en';

export const UI_TEXT = {
  en: {
    'site.title': 'Espai.ai',
    'site.description': 'AI-powered business process optimization',
    // SEO Meta Descriptions
    'meta.home.description': 'Transform your business with AI-powered process automation. Record, analyze, and optimize your workflows automatically. Pay per device, save time instantly.',
    'meta.about.description': 'Learn about Espai.ai\'s mission to revolutionize business processes with AI. Discover how we help companies optimize operations and unlock their potential.',
    'meta.pricing.description': 'Transparent per-device pricing for AI business automation. Pay only when you start saving time. Plans from €70-100/device/month plus automation fees.',
    'meta.faq.description': 'Frequently asked questions about Espai.ai AI automation platform. Learn how our process recording, analysis, and optimization works for your business.',
    'meta.contact.description': 'Contact Espai.ai team for AI business automation consultation. Get started with intelligent process optimization and workflow automation today.',
    'meta.privacy.description': 'Espai.ai privacy policy and data protection practices. Learn how we secure your business data in our AI process automation platform.',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.pricing': 'Pricing',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.resources': 'Resources',
    'nav.privacy': 'Privacy Policy',
    'hero.title': 'Optimize Your Business Processes with AI',
    'hero.subtitle': 'Discover bottlenecks, automate workflows, and unlock your company\'s potential with intelligent process analysis',
    'hero.cta': 'Get Started',
    'hero.cta.secondary': 'Learn More',
    'footer.rights': 'All rights reserved.',
    'footer.crafted': 'crafted with ♡ in barcelona',
    // Contact form translations
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Ready to transform your business? Get in touch with our team',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.company': 'Company Name',
    'contact.form.phone': 'Phone Number',
    'contact.form.employees': 'Number of Employees',
    'contact.form.employees.option1': '1-10 employees',
    'contact.form.employees.option2': '11-50 employees',
    'contact.form.employees.option3': '51-200 employees',
    'contact.form.employees.option4': '200+ employees',
    'contact.form.interest': 'I\'m interested in',
    'contact.form.interest.demo': 'Schedule Demo',
    'contact.form.interest.pricing': 'Pricing Information',
    'contact.form.interest.other': 'Other',
    'contact.form.message': 'Tell us about your business needs',
    'contact.form.submit': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully! We\'ll get back to you soon.',
    'contact.form.error': 'Error sending message. Please try again or contact us directly.',
    'contact.form.required': 'This field is required',
    // Language detection translations
    'lang.detection.title': 'Language Preference',
    'lang.detection.message': 'We detected your browser language is {language}. Would you like to switch to this language?',
    'lang.detection.switch': 'Switch to {language}',
    'lang.detection.stay': 'Stay in English',
    'lang.detection.dismiss': 'Don\'t ask again'
  },
  es: {
    'site.title': 'Espai.ai',
    'site.description': 'Optimización de procesos empresariales con IA',
    // SEO Meta Descriptions
    'meta.home.description': 'Transforma tu negocio con automatización de procesos con IA. Registra, analiza y optimiza tus flujos de trabajo de forma automática. Paga por dispositivo, ahorra tiempo instantáneamente.',
    'meta.about.description': 'Aprende sobre la misión de Espai.ai para revolucionar los procesos empresariales con IA. Descubre cómo ayudamos a las empresas a optimizar sus operaciones y desbloquear su potencial.',
    'meta.pricing.description': 'Precios transparentes por dispositivo para la automatización de negocios con IA. Paga solo cuando empieces a ahorrar tiempo. Planes desde €70-100/dispositivo/mes más tarifas de automatización.',
    'meta.faq.description': 'Preguntas frecuentes sobre la plataforma de automatización de procesos de Espai.ai. Aprende cómo funciona nuestro registro, análisis y optimización de procesos para tu negocio.',
    'meta.contact.description': 'Contacta con el equipo de Espai.ai para una consulta sobre la automatización de negocios con IA. ¡Comienza con la optimización inteligente de procesos y la automatización de flujos de trabajo hoy!',
    'meta.privacy.description': 'Política de privacidad y prácticas de protección de datos de Espai.ai. Aprende cómo protegemos tus datos de negocio en nuestra plataforma de automatización de procesos con IA.',
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.pricing': 'Precios',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contacto',
    'nav.resources': 'Recursos',
    'nav.privacy': 'Política de Privacidad',
    'hero.title': 'Optimiza tus Procesos Empresariales con IA',
    'hero.subtitle': 'Descubre cuellos de botella, automatiza flujos de trabajo y desbloquea el potencial de tu empresa con análisis inteligente de procesos',
    'hero.cta': 'Comenzar',
    'hero.cta.secondary': 'Saber Más',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.crafted': 'creado con ♡ en barcelona',
    // Contact form translations
    'contact.title': 'Contacta con Nosotros',
    'contact.subtitle': '¿Listo para transformar tu negocio? Ponte en contacto con nuestro equipo',
    'contact.form.name': 'Nombre Completo',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.company': 'Nombre de la Empresa',
    'contact.form.phone': 'Número de Teléfono',
    'contact.form.employees': 'Número de Empleados',
    'contact.form.employees.option1': '1-10 empleados',
    'contact.form.employees.option2': '11-50 empleados',
    'contact.form.employees.option3': '51-200 empleados',
    'contact.form.employees.option4': '200+ empleados',
    'contact.form.interest': 'Estoy interesado en',
    'contact.form.interest.demo': 'Programar Demo',
    'contact.form.interest.pricing': 'Información de Precios',
    'contact.form.interest.other': 'Otro',
    'contact.form.message': 'Cuéntanos sobre las necesidades de tu negocio',
    'contact.form.submit': 'Enviar Mensaje',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': '¡Mensaje enviado con éxito! Te contactaremos pronto.',
    'contact.form.error': 'Error al enviar el mensaje. Por favor intenta de nuevo o contáctanos directamente.',
    'contact.form.required': 'Este campo es obligatorio',
    // Language detection translations
    'lang.detection.title': 'Preferencia de Idioma',
    'lang.detection.message': 'Detectamos que tu navegador está en {language}. ¿Te gustaría cambiar a este idioma?',
    'lang.detection.switch': 'Cambiar a {language}',
    'lang.detection.stay': 'Quedarse en Inglés',
    'lang.detection.dismiss': 'No preguntar de nuevo'
  },
  ca: {
    'site.title': 'Espai.ai',
    'site.description': 'Optimització de processos empresarials amb IA',
    // SEO Meta Descriptions
    'meta.home.description': 'Optimitza el teu negoci amb automatització de processos amb IA. Registra, analitza i optimitza els teus fluxos de treball de forma automàtica. Paga per dispositiu, ahorra temps instantàniament.',
    'meta.about.description': 'Aprendeu sobre la missió d\'Espai.ai per revolucionar els processos empresarials amb IA. Descubreu com ens ajudem les empreses a optimitzar les seves operacions i desbloqueu el seu potencial.',
    'meta.pricing.description': 'Preus transparents per dispositiu per a l\'automatització d\'empreses amb IA. Paga només quan comences a estalviar temps. Plans des de €70-100/dispositiu/mes més tarifes d\'automatització.',
    'meta.faq.description': 'Preguntes freqüents sobre la plataforma d\'automatització de processos d\'Espai.ai. Apreneu com funciona el nostre registre, anàlisi i optimització de processos per al teu negoci.',
    'meta.contact.description': 'Contacta amb l\'equip d\'Espai.ai per a una consulta sobre l\'automatització d\'empreses amb IA. ¡Comenceu amb l\'optimització intel·ligent de processos i l\'automatització de fluxos de treball avui!',
    'meta.privacy.description': 'Política de privacitat i pràctiques de protecció de dades d\'Espai.ai. Apreneu com protegim els teus dades de negoci a la nostra plataforma d\'automatització de processos amb IA.',
    'nav.home': 'Inici',
    'nav.about': 'Sobre nosaltres',
    'nav.pricing': 'Preus',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contacte',
    'nav.resources': 'Recursos',
    'nav.privacy': 'Política de Privacitat',
    'hero.title': 'Optimitza els teus Processos Empresarials amb IA',
    'hero.subtitle': 'Descobreix colls d\'ampolla, automatitza fluxos de treball i desbloqueja el potencial de la teva empresa amb anàlisi intel·ligent de processos',
    'hero.cta': 'Començar',
    'hero.cta.secondary': 'Saber-ne Més',
    'footer.rights': 'Tots els drets reservats.',
    'footer.crafted': 'fet amb ♡ a barcelona',
    // Contact form translations
    'contact.title': 'Contacta amb Nosaltres',
    'contact.subtitle': 'Preparat per transformar el teu negoci? Posa\'t en contacte amb el nostre equip',
    'contact.form.name': 'Nom Complet',
    'contact.form.email': 'Correu Electrònic',
    'contact.form.company': 'Nom de l\'Empresa',
    'contact.form.phone': 'Número de Telèfon',
    'contact.form.employees': 'Número d\'Empleats',
    'contact.form.employees.option1': '1-10 empleats',
    'contact.form.employees.option2': '11-50 empleats',
    'contact.form.employees.option3': '51-200 empleats',
    'contact.form.employees.option4': '200+ empleats',
    'contact.form.interest': 'Estic interessat en',
    'contact.form.interest.demo': 'Programar Demo',
    'contact.form.interest.pricing': 'Informació de Preus',
    'contact.form.interest.other': 'Altre',
    'contact.form.message': 'Explica\'ns sobre les necessitats del teu negoci',
    'contact.form.submit': 'Enviar Missatge',
    'contact.form.sending': 'Enviant...',
    'contact.form.success': 'Missatge enviat amb èxit! Et contactarem aviat.',
    'contact.form.error': 'Error en enviar el missatge. Si us plau intenta de nou o contacta\'ns directament.',
    'contact.form.required': 'Aquest camp és obligatori',
    // Language detection translations
    'lang.detection.title': 'Preferència d\'Idioma',
    'lang.detection.message': 'Hem detectat que el teu navegador està en {language}. Vols canviar a aquest idioma?',
    'lang.detection.switch': 'Canviar a {language}',
    'lang.detection.stay': 'Quedar-se en Anglès',
    'lang.detection.dismiss': 'No tornar a preguntar'
  },
  de: {
    'site.title': 'Espai.ai',
    'site.description': 'KI-gestützte Optimierung von Geschäftsprozessen',
    // SEO Meta Descriptions
    'meta.home.description': 'Optimieren Sie Ihren Geschäftsprozess mit intelligenten Automatisierungsfunktionen. Prozessaufzeichnung, Analyse und Optimierung Ihrer Arbeitsabläufe automatisch. Kosten pro Gerät, Zeit sparen Sie sofort.',
    'meta.about.description': 'Erfahren Sie mehr über die Mission von Espai.ai, um Geschäftsprozesse mit KI zu revolutionieren. Entdecken Sie, wie wir Unternehmen dabei unterstützen, ihre Operationen zu optimieren und ihr Potenzial zu entfalten.',
    'meta.pricing.description': 'Transparente Preise pro Gerät für intelligentes Unternehmensautomatisierung. Zahlung nur, wenn Sie mit der Zeit sparen. Pläne ab €70-100/Gerät/Monat plus Automatisierungsgebühren.',
    'meta.faq.description': 'Häufig gestellte Fragen zur KI-Automatisierungsplattform von Espai.ai. Erfahren Sie, wie unser Prozessaufzeichnung, Analyse und Optimierung für Ihr Unternehmen funktioniert.',
    'meta.contact.description': 'Kontaktieren Sie den Espai.ai-Team für eine Beratung zur intelligenten Unternehmensautomatisierung. Beginnen Sie heute mit intelligenten Prozessoptimierung und Workflow-Automatisierung!',
    'meta.privacy.description': 'Datenschutzerklärung und Datenschutzpraxis von Espai.ai. Erfahren Sie, wie wir Ihre Geschäftedaten in unserer KI-Prozessautomatisierungsplattform sichern.',
    'nav.home': 'Startseite',
    'nav.about': 'Über uns',
    'nav.pricing': 'Preise',
    'nav.faq': 'FAQ',
    'nav.contact': 'Kontakt',
    'nav.resources': 'Ressourcen',
    'nav.privacy': 'Datenschutzerklärung',
    'hero.title': 'Optimieren Sie Ihre Geschäftsprozesse mit KI',
    'hero.subtitle': 'Entdecken Sie Engpässe, automatisieren Sie Arbeitsabläufe und erschließen Sie das Potenzial Ihres Unternehmens mit intelligenter Prozessanalyse',
    'hero.cta': 'Loslegen',
    'hero.cta.secondary': 'Mehr erfahren',
    'footer.rights': 'Alle Rechte vorbehalten.',
    'footer.crafted': 'gemacht mit ♡ in barcelona',
    // Contact form translations
    'contact.title': 'Kontaktieren Sie uns',
    'contact.subtitle': 'Bereit, Ihr Unternehmen zu transformieren? Nehmen Sie Kontakt mit unserem Team auf',
    'contact.form.name': 'Vollständiger Name',
    'contact.form.email': 'E-Mail-Adresse',
    'contact.form.company': 'Firmenname',
    'contact.form.phone': 'Telefonnummer',
    'contact.form.employees': 'Anzahl der Mitarbeiter',
    'contact.form.employees.option1': '1-10 Mitarbeiter',
    'contact.form.employees.option2': '11-50 Mitarbeiter',
    'contact.form.employees.option3': '51-200 Mitarbeiter',
    'contact.form.employees.option4': '200+ Mitarbeiter',
    'contact.form.interest': 'Ich bin interessiert an',
    'contact.form.interest.demo': 'Demo planen',
    'contact.form.interest.pricing': 'Preisinformationen',
    'contact.form.interest.other': 'Andere',
    'contact.form.message': 'Erzählen Sie uns von Ihren Geschäftsanforderungen',
    'contact.form.submit': 'Nachricht senden',
    'contact.form.sending': 'Wird gesendet...',
    'contact.form.success': 'Nachricht erfolgreich gesendet! Wir werden uns bald bei Ihnen melden.',
    'contact.form.error': 'Fehler beim Senden der Nachricht. Bitte versuchen Sie es erneut oder kontaktieren Sie uns direkt.',
    'contact.form.required': 'Dieses Feld ist erforderlich',
    // Language detection translations
    'lang.detection.title': 'Spracheinstellung',
    'lang.detection.message': 'Wir haben erkannt, dass Ihr Browser auf {language} eingestellt ist. Möchten Sie zu dieser Sprache wechseln?',
    'lang.detection.switch': 'Zu {language} wechseln',
    'lang.detection.stay': 'Bei Englisch bleiben',
    'lang.detection.dismiss': 'Nicht mehr fragen'
  }
};
