// Place any global data in this file.
// You can import this data from anywhere in your site by using the `import` keyword.

export const SITE_TITLE = 'Espai.ai';
export const SITE_DESCRIPTION = 'AI-powered business process optimization';

export const LANGUAGES = {
  en: 'English',
  es: 'Español', 
  ca: 'Català',
  de: 'Deutsch'
};

export const DEFAULT_LANG = 'en';

export const UI_TEXT = {
  en: {
    'site.title': 'Espai.ai',
    'site.description': 'AI-powered business process optimization',
    // SEO Meta Descriptions
    'meta.home.description': 'Stop wasting time on repetitive tasks. Espai.ai records your processes, finds inefficiencies with AI, and creates automations that save 20+ hours per week. Pay only when you start saving.',
    'meta.about.description': 'Espai.ai helps businesses eliminate manual work through intelligent process automation. We\'ve helped companies save 40% of employee time and reduce operational costs by 30%.',
    'meta.pricing.description': 'Transparent pricing: €70-100 per device per month. You pay only after automations start saving you time. Most companies see ROI within 30 days.',
    'meta.faq.description': 'Get answers about Espai.ai\'s AI automation platform. Learn how our process recording and analysis can save your business 20+ hours per week.',
    'meta.contact.description': 'Ready to save 20+ hours per week? Contact Espai.ai for a free process analysis. See how AI automation can transform your business operations.',
    'meta.privacy.description': 'Espai.ai privacy policy and data protection practices. Learn how we secure your business data in our AI process automation platform.',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.pricing': 'Pricing',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.resources': 'Resources',
    'nav.privacy': 'Privacy Policy',
    'hero.title': 'Save 20+ Hours Per Week with AI Automation',
    'hero.subtitle': 'Stop wasting time on repetitive tasks. Our AI records your processes, finds inefficiencies, and creates automations that actually work.',
    'hero.cta': 'Start Free Analysis',
    'hero.cta.secondary': 'See How It Works',
    'footer.rights': 'All rights reserved.',
    'footer.crafted': 'crafted with ♡ in barcelona',
    // Contact form translations
    'contact.title': 'Get Your Free Process Analysis',
    'contact.subtitle': 'See how much time your business can save with AI automation',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.company': 'Company Name',
    'contact.form.phone': 'Phone Number',
    'contact.form.employees': 'Number of Employees',
    'contact.form.employees.option1': '1-10 employees',
    'contact.form.employees.option2': '11-50 employees',
    'contact.form.employees.option3': '51-200 employees',
    'contact.form.employees.option4': '200+ employees',
    'contact.form.interest': 'I\'m interested in',
    'contact.form.interest.demo': 'Free Process Analysis',
    'contact.form.interest.pricing': 'Pricing Information',
    'contact.form.interest.other': 'Other',
    'contact.form.message': 'Tell us about your current processes and pain points',
    'contact.form.submit': 'Get Free Analysis',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully! We\'ll contact you within 24 hours to schedule your free analysis.',
    'contact.form.error': 'Error sending message. Please try again or contact us directly.',
    'contact.form.required': 'This field is required',
    // Language detection translations
    'lang.detection.title': 'Language Preference',
    'lang.detection.message': 'We detected your browser language is {language}. Would you like to switch to this language?',
    'lang.detection.switch': 'Switch to {language}',
    'lang.detection.stay': 'Stay in English',
    'lang.detection.dismiss': 'Don\'t ask again'
  },
  es: {
    'site.title': 'Espai.ai',
    'site.description': 'Optimización de procesos empresariales con IA',
    // SEO Meta Descriptions
    'meta.home.description': 'Deja de perder tiempo en tareas repetitivas. Espai.ai registra tus procesos, encuentra ineficiencias con IA y crea automatizaciones que ahorran más de 20 horas por semana. Paga solo cuando empieces a ahorrar.',
    'meta.about.description': 'Espai.ai ayuda a las empresas a eliminar el trabajo manual mediante automatización inteligente de procesos. Hemos ayudado a empresas a ahorrar 40% del tiempo de empleados y reducir costos operativos en 30%.',
    'meta.pricing.description': 'Precios transparentes: €70-100 por dispositivo por mes. Pagas solo después de que las automatizaciones empiecen a ahorrarte tiempo. La mayoría de empresas ven ROI en 30 días.',
    'meta.faq.description': 'Obtén respuestas sobre la plataforma de automatización IA de Espai.ai. Aprende cómo nuestro registro y análisis de procesos puede ahorrarle a tu empresa más de 20 horas por semana.',
    'meta.contact.description': '¿Listo para ahorrar más de 20 horas por semana? Contacta Espai.ai para un análisis gratuito de procesos. Ve cómo la automatización IA puede transformar tus operaciones.',
    'meta.privacy.description': 'Política de privacidad y prácticas de protección de datos de Espai.ai. Aprende cómo protegemos tus datos de negocio en nuestra plataforma de automatización de procesos con IA.',
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.pricing': 'Precios',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contacto',
    'nav.resources': 'Recursos',
    'nav.privacy': 'Política de Privacidad',
    'hero.title': 'Ahorra más de 20 horas por semana con automatización IA',
    'hero.subtitle': 'Deja de perder tiempo en tareas repetitivas. Nuestra IA registra tus procesos, encuentra ineficiencias y crea automatizaciones que realmente funcionan.',
    'hero.cta': 'Análisis Gratuito',
    'hero.cta.secondary': 'Ver Cómo Funciona',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.crafted': 'creado con ♡ en barcelona',
    // Contact form translations
    'contact.title': 'Obtén tu análisis gratuito de procesos',
    'contact.subtitle': 'Ve cuánto tiempo puede ahorrar tu empresa con automatización IA',
    'contact.form.name': 'Nombre completo',
    'contact.form.email': 'Correo electrónico',
    'contact.form.company': 'Nombre de la empresa',
    'contact.form.phone': 'Número de teléfono',
    'contact.form.employees': 'Número de empleados',
    'contact.form.employees.option1': '1-10 empleados',
    'contact.form.employees.option2': '11-50 empleados',
    'contact.form.employees.option3': '51-200 empleados',
    'contact.form.employees.option4': '200+ empleados',
    'contact.form.interest': 'Estoy interesado en',
    'contact.form.interest.demo': 'Análisis Gratuito de Procesos',
    'contact.form.interest.pricing': 'Información de Precios',
    'contact.form.interest.other': 'Otro',
    'contact.form.message': 'Cuéntanos sobre tus procesos actuales y problemas',
    'contact.form.submit': 'Obtener Análisis Gratuito',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': '¡Mensaje enviado con éxito! Te contactaremos en 24 horas para programar tu análisis gratuito.',
    'contact.form.error': 'Error al enviar el mensaje. Por favor intenta de nuevo o contáctanos directamente.',
    'contact.form.required': 'Este campo es obligatorio',
    // Language detection translations
    'lang.detection.title': 'Preferencia de Idioma',
    'lang.detection.message': 'Detectamos que tu navegador está en {language}. ¿Te gustaría cambiar a este idioma?',
    'lang.detection.switch': 'Cambiar a {language}',
    'lang.detection.stay': 'Quedarse en Inglés',
    'lang.detection.dismiss': 'No preguntar de nuevo'
  },
  ca: {
    'site.title': 'Espai.ai',
    'site.description': 'Optimització de processos empresarials amb IA',
    // SEO Meta Descriptions
    'meta.home.description': 'Deixa de perdre temps en tasques repetitives. Espai.ai registra els teus processos, troba ineficiències amb IA i crea automatitzacions que estalvien més de 20 hores per setmana. Paga només quan comences a estalviar.',
    'meta.about.description': 'Espai.ai ajuda les empreses a eliminar el treball manual mitjançant automatització intel·ligent de processos. Hem ajudat empreses a estalviar 40% del temps d\'empleats i reduir costos operatius en 30%.',
    'meta.pricing.description': 'Preus transparents: €70-100 per dispositiu per mes. Pagues només després que les automatitzacions comencin a estalviar-te temps. La majoria d\'empreses veuen ROI en 30 dies.',
    'meta.faq.description': 'Obten respostes sobre la plataforma d\'automatització IA d\'Espai.ai. Aprèn com el nostre registre i anàlisi de processos pot estalviar a la teva empresa més de 20 hores per setmana.',
    'meta.contact.description': 'Preparat per estalviar més de 20 hores per setmana? Contacta Espai.ai per una anàlisi gratuïta de processos. Veu com l\'automatització IA pot transformar les teves operacions.',
    'meta.privacy.description': 'Política de privacitat i pràctiques de protecció de dades d\'Espai.ai. Aprèn com protegim les teves dades de negoci a la nostra plataforma d\'automatització de processos amb IA.',
    'nav.home': 'Inici',
    'nav.about': 'Sobre nosaltres',
    'nav.pricing': 'Preus',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contacte',
    'nav.resources': 'Recursos',
    'nav.privacy': 'Política de Privacitat',
    'hero.title': 'Estalvia més de 20 hores per setmana amb automatització IA',
    'hero.subtitle': 'Deixa de perdre temps en tasques repetitives. La nostra IA registra els teus processos, troba ineficiències i crea automatitzacions que realment funcionen.',
    'hero.cta': 'Anàlisi Gratuïta',
    'hero.cta.secondary': 'Veure Com Funciona',
    'footer.rights': 'Tots els drets reservats.',
    'footer.crafted': 'fet amb ♡ a barcelona',
    // Video section translations
    'video.section.title': 'Veu com estalviem més de 20 hores setmanals a les empreses',
    'video.section.subtitle': 'Mira el nostre demo de 2 minuts per veure com Espai.ai identifica ineficiències i crea automatitzacions que realment funcionen.',
    'video.demo.title': 'Veure Demo de 2 Minuts',
    'video.demo.subtitle': 'Veure resultats reals en acció',
    // Features section translations
    'features.section.title': 'Com et estalviem més de 20 hores setmanals',
    'features.section.subtitle': 'La nostra IA fa la feina pesada - tu obtens els resultats',
    'features.recording.title': 'Registra Tot Automàticament',
    'features.recording.description': 'El nostre programari registra silenciosament tots els esdeveniments del sistema i accions de l\'usuari. No cal configuració - només instal·lar i comença a funcionar immediatament.',
    'features.automation.title': 'IA Troba Ineficiències Ocultes',
    'features.automation.description': 'La nostra IA analitza els teus processos i identifica exactament on es perd temps. Obten recomanacions específiques per oportunitats d\'automatització.',
    'features.insights.title': 'Crea Automatitzacions Que Funcionen',
    'features.insights.description': 'No només suggerim millores - construïm les automatitzacions per tu. La majoria d\'empreses veuen els seus primers estalvis de temps durant el segon o quart mes, depenent del sector i la complexitat dels processos.',
    // How it works section translations
    'howitworks.section.title': '3 passos simples per estalviar més de 20 hores setmanals',
    'howitworks.section.subtitle': 'No cal coneixement tècnic - nosaltres ens encarreguem de tot',
    'howitworks.step1.title': 'Instal·lar i Registrar (Dia 1)',
    'howitworks.step1.description': 'Instal·lem el nostre programari als teus sistemes. Immediatament comença a registrar tots els processos i accions de l\'usuari. No cal configuració ni formació.',
    'howitworks.step2.title': 'Anàlisi IA (Setmana 1-2)',
    'howitworks.step2.description': 'La nostra IA analitza les teves dades i identifica ineficiències específiques. Obten un informe detallat que mostra exactament on es perd temps.',
    'howitworks.step3.title': 'Automatització i Estalvis (Setmana 2-4)',
    'howitworks.step3.description': 'Construïm i despleguem automatitzacions per als teus majors perdents de temps. Comences a veure estalvis reals de temps immediatament. Paga només després de començar a estalviar.',
    // Value proposition section translations
    'value.section.title': 'Per què les empreses trien Espai.ai',
    'value.section.subtitle': 'Resultats reals, no promeses buides',
    'value.installation.title': '🚀 Implementació Sense Risc',
    'value.installation.description': 'No pagues res fins que les automatitzacions comencin a estalviar-te temps. La majoria d\'empreses veuen ROI durant el segon o quart mes, depenent del sector i la complexitat dels processos. Sense costos inicials, sense contractes a llarg termini.',
    'value.pricing.title': '💰 Estalvis de Temps Provats',
    'value.pricing.description': 'Els nostres clients estalvien una mitjana de més de 20 hores setmanals. Això són més de 1.040 hores per any - equivalent a contractar un empleat addicional a temps complet.',
    // CTA section translations
    'cta.section.title': 'Preparat per estalviar més de 20 hores setmanals?',
    'cta.section.subtitle': 'Uneix-te a les empreses que estan eliminant la feina manual amb automatització IA',
    'cta.analysis': 'Obtenir Anàlisi Gratuïta de Processos',
    'cta.demo': 'Veure Preus',
    // Contact form translations
    'contact.title': 'Obten la teva anàlisi gratuïta de processos',
    'contact.subtitle': 'Veus quant temps pot estalviar la teva empresa amb automatització IA',
    'contact.form.name': 'Nom complet',
    'contact.form.email': 'Correu electrònic',
    'contact.form.company': 'Nom de l\'empresa',
    'contact.form.phone': 'Número de telèfon',
    'contact.form.employees': 'Número d\'empleats',
    'contact.form.employees.option1': '1-10 empleats',
    'contact.form.employees.option2': '11-50 empleats',
    'contact.form.employees.option3': '51-200 empleats',
    'contact.form.employees.option4': '200+ empleats',
    'contact.form.interest': 'Estic interessat en',
    'contact.form.interest.demo': 'Anàlisi Gratuïta de Processos',
    'contact.form.interest.pricing': 'Informació de Preus',
    'contact.form.interest.other': 'Altre',
    'contact.form.message': 'Explica\'ns sobre els teus processos actuals i problemes',
    'contact.form.submit': 'Obtenir Anàlisi Gratuïta',
    'contact.form.sending': 'Enviant...',
    'contact.form.success': 'Missatge enviat amb èxit! Et contactarem en 24 hores per programar la teva anàlisi gratuïta.',
    'contact.form.error': 'Error en enviar el missatge. Si us plau intenta de nou o contacta\'ns directament.',
    'contact.form.required': 'Aquest camp és obligatori',
    // Language detection translations
    'lang.detection.title': 'Preferència d\'Idioma',
    'lang.detection.message': 'Hem detectat que el teu navegador està en {language}. Vols canviar a aquest idioma?',
    'lang.detection.switch': 'Canviar a {language}',
    'lang.detection.stay': 'Quedar-se en Anglès',
    'lang.detection.dismiss': 'No tornar a preguntar',
    // About page translations
    'about.hero.title': 'Ajudem les empreses a estalviar més de 20 hores per setmana',
    'about.hero.subtitle': 'Les empreses estan eliminant la feina manual amb la nostra plataforma d\'automatització IA',
    'about.results.title': 'Els nostres resultats',
    'about.results.description': 'Les empreses que utilitzen Espai.ai estalvien una mitjana de més de 20 hores per setmana. Això són més de 1.040 hores per any - equivalent a contractar un empleat addicional sense els costos generals.',
    'about.approach.title': 'El nostre enfocament',
    'about.approach.description': 'No només analitzem els teus processos - construïm automatitzacions que funcionen i eliminen tasques repetitives. Pagues només després de començar a veure estalvis reals de temps.',
    'about.whatwedo.title': 'El que realment fem',
    'about.whatwedo.record.title': 'Registrem Tot',
    'about.whatwedo.record.description': 'El nostre programari registra silenciosament tots els esdeveniments del sistema i accions de l\'usuari. No cal configuració - només instal·lar i comença a funcionar immediatament.',
    'about.whatwedo.find.title': 'Trobem Ineficiències',
    'about.whatwedo.find.description': 'La nostra IA analitza les teves dades i identifica exactament on es perd temps. Obten recomanacions específiques per oportunitats d\'automatització.',
    'about.whatwedo.build.title': 'Construïm Automatitzacions',
    'about.whatwedo.build.description': 'No només suggerim millores - construïm les automatitzacions per tu. La majoria d\'empreses veuen els seus primers estalvis de temps durant el segon o quart mes, depenent del sector i la complexitat dels processos.',
    // Pricing page translations
    'pricing.hero.title': 'Paga Només Quan Comencis a Estalviar Temps',
    'pricing.hero.subtitle': 'Preus transparents sense costos inicials. Pagues només després que les automatitzacions comencin a generar estalvis reals.',
    'pricing.guarantee': '🎯 Garantia Sense Risc: No pagues res fins que les nostres automatitzacions comencin a estalviar-te temps. La majoria d\'empreses veuen els seus primers estalvis durant el segon o quart mes, depenent del sector i la complexitat dels processos. Sense costos inicials, sense contractes a llarg termini.',
    'pricing.basic.title': 'Bàsic',
    'pricing.basic.price': '100',
    'pricing.basic.period': '/dispositiu/mes',
    'pricing.basic.devices': 'Fins a 10 dispositius',
    'pricing.basic.features': [
      'Registre automàtic de processos',
      'Detecció d\'ineficiències amb IA',
      'Desenvolupament d\'automatitzacions personalitzades',
      'Dashboards de rendiment en temps real',
      'Automatitzacions il·limitades',
      'Instal·lació i configuració completa'
    ],
    'pricing.basic.automation': '+ €18/mes per automatització',
    'pricing.pro.title': 'Pro',
    'pricing.pro.price': '80',
    'pricing.pro.period': '/dispositiu/mes',
    'pricing.pro.devices': 'A partir de 15 dispositius',
    'pricing.pro.features': [
      'Tot el que inclou Bàsic',
      'Accés a aplicació mòbil',
      'Suport prioritari',
      'Analytics avançats'
    ],
    'pricing.pro.automation': '+ €8/mes per automatització',
    'pricing.advanced.title': 'Pro Avançat',
    'pricing.advanced.price': '70',
    'pricing.advanced.period': '/dispositiu/mes',
    'pricing.advanced.devices': 'A partir de 30 dispositius',
    'pricing.advanced.features': [
      'Tot el que inclou Pro',
      'Suport dedicat 24/7',
      'Fluxos de treball d\'automatització complexos',
      'Integracions personalitzades'
    ],
    'pricing.advanced.automation': '+ €5/mes per automatització',
    'pricing.popular': 'Més Popular',
    'pricing.cta': 'Iniciar Anàlisi Gratuïta',
    'pricing.roi.title': '💰 Calculadora de ROI',
    'pricing.roi.description': 'Si estalvies només 20 hores per setmana (la nostra mitjana), això val €2,000+ per mes en temps d\'empleats. La nostra solució t\'ajuda a començar a automatitzar processos i generar estalvis segons les teves necessitats específiques i la complexitat dels teus fluxos de treball.',
    'pricing.setup.title': '🚀 Sense Complicacions de Configuració',
    'pricing.setup.description': 'Nosaltres gestionem tot: instal·lació, configuració i desenvolupament d\'automatitzacions. Tu et centres en el teu negoci mentre optimitzem els teus processos.',
    'pricing.pilot.title': '📋 Avís de Projecte Pilot',
    'pricing.pilot.description': 'Actualment estem en la fase pilot del nostre projecte, per la qual cosa els nostres preus són actualment més baixos. La nostra política de preus pot ser modificada en el futur. Els clients amb preus existents mantindran les seves tarifes actuals durant un any a partir de la data de qualsevol modificació.',
    // FAQ page translations
    'faq.hero.title': 'Preguntes Freqüents',
    'faq.hero.subtitle': 'Tot el que necessites saber per estalviar més de 20 hores setmanals amb automatització d\'IA',
    'faq.category.howitworks': 'Com Funciona',
    'faq.category.pricing': 'Preus & ROI',
    'faq.category.implementation': 'Implementació',
    'faq.question.timesavings': 'Com m\'estalvia temps Espai.ai realment?',
    'faq.answer.timesavings': 'La nostra IA grava tots els teus processos, identifica tasques repetitives i construeix automatitzacions personalitzades que eliminen el treball manual. La majoria d\'empreses estalvien més de 20 hores setmanals - és com contractar un empleat extra sense els costos generals.',
    'faq.question.privacy': 'Les meves dades estan segures i són privades?',
    'faq.answer.privacy': 'Absolutament. Les teves dades mai surten dels teus sistemes i mai són vistes per humans. Només les utilitzem per construir automatitzacions per a tu. Si alguna vegada volem usar les teves dades per una altra cosa, et demanarem permís explícit primer.',
    'faq.question.results': 'Com de ràpid veuré resultats?',
    'faq.answer.results': 'La majoria d\'empreses comencen a veure estalvis de temps durant el segon o quart mes, depenent del sector i la complexitat dels processos. La nostra IA necessita temps per analitzar els teus processos i construir automatitzacions efectives. Rebràs informes detallats que mostren exactament quant temps estalvia cada automatització.',
    'faq.question.cost': 'Quin és el cost real i el ROI?',
    'faq.answer.cost': 'Pagues 70-100€ per dispositiu per mes, més petites taxes per automatització. Si només estalvies 20 hores setmanals (la nostra mitjana), això val 2.000€+ per mes en temps d\'empleat. La majoria d\'empreses veuen ROI durant el segon o quart mes, depenent del sector i la complexitat dels processos.',
    'faq.question.noresults': 'Què passa si no veig cap estalvi?',
    'faq.answer.noresults': 'No pagues res fins que les automatitzacions comencin a estalviar-te temps. Si no podem lliurar resultats, no pagues. És així de simple. Estem segurs que podem ajudar-te a estalviar temps, o no pagues.',
    'faq.question.cancel': 'Puc cancel·lar en qualsevol moment?',
    'faq.answer.cancel': 'Sí, sense contractes a llarg termini. Pots cancel·lar en qualsevol moment, tot i que la majoria de clients veuen estalvis tan significatius que mai volen parar. Un cop vegis quant temps estàs estalviant, et preguntaràs com mai has treballat sense això.',
    'faq.question.setup': 'Com de complicada és la configuració?',
    'faq.answer.setup': 'No és complicada en absolut. Ens encarreguem de tot: instal·lació, configuració i desenvolupament d\'automatitzacions. No necessites cap coneixement tècnic. Només fes-nos saber quan estàs preparat per començar a estalviar temps.',
    'faq.question.support': 'Quin tipus de suport proporcioneu?',
    'faq.answer.support': 'Proporcionem suport complet durant tot el procés. Des de la configuració inicial fins a l\'optimització contínua, el nostre equip està aquí per ajudar. Els plans Pro i Pro Advanced inclouen suport prioritari i gestors de compte dedicats.',
    'faq.question.workflow': 'Això interromprà el meu flux de treball actual?',
    'faq.answer.workflow': 'Cap interrupció en absolut. El nostre programari s\'executa silenciosament en segon pla, gravant processos sense interferir amb el teu treball. Les automatitzacions s\'implementen gradualment i només després de proves exhaustives per assegurar que funcionen perfectament.',
    'faq.category.results': 'Resultats & Èxit',
    'faq.question.results.other': 'Quin tipus de resultats veuen altres empreses?',
    'faq.answer.results.other': 'Els nostres clients estalvien una mitjana de més de 20 hores setmanals. Això són més de 1.040 hores per any - equivalent a contractar un empleat addicional a temps complet. Moltes empreses també informen de millora en la precisió i reducció d\'errors.',
    'faq.question.metrics': 'Com mesureu l\'èxit?',
    'faq.answer.metrics': 'Rastrejem el temps real gastat en tasques abans i després de l\'automatització. Rebràs informes detallats que mostren exactament quant temps estalvia cada automatització, més mètriques sobre millores en la precisió i reducció d\'errors.',
    'faq.question.customizations': 'Què passa si necessito automatitzacions personalitzades?',
    'faq.answer.customizations': 'Construïm automatitzacions personalitzades per a les teves necessitats específiques. La nostra IA analitza els teus processos únics i crea solucions a mida. Els plans Pro Advanced inclouen automatització de flux de treball complex i integracions personalitzades.',
    // Contact page additional translations
    'contact.demo.title': '📊 Anàlisi Gratuïta de Processos',
    'contact.demo.description': 'Veu Espai.ai en acció amb una demo personalitzada adaptada a la teva indústria i necessitats empresarials.',
    'contact.consent.text': 'He llegit i accepto la',
    'contact.consent.link': 'política de tractament de dades',
    'contact.select.placeholder': 'Seleccionar...',
    'contact.error.consent': 'Has d\'acceptar la política de tractament de dades',
    // Privacy page translations
    'privacy.title': 'Política de Privacitat',
    'privacy.subtitle': 'Aquesta pàgina està en construcció. El text legal s\'afegirà aviat.',
    // Additional FAQ and contact page translations
    'faq.cta.title': 'Preparat per començar a estalviar temps?',
    'faq.cta.subtitle': 'Obten la teva anàlisi de processos gratuïta i veu quant temps pots estalviar',
    'contact.pricing.description': 'Paga per dispositiu, no per automatització. Sense pagament fins que comencis a veure estalvis reals de temps amb les nostres automatitzacions.',
    'contact.solutions.description': 'Transforma els teus processos empresarials amb automatització impulsada per IA. Les nostres solucions s\'adapten a les teves necessitats específiques i requisits de la indústria.',
    'contact.email.success': 'Client d\'email obert. Si us plau envia l\'email per completar la teva sol·licitud.'
  },
  de: {
    'site.title': 'Espai.ai',
    'site.description': 'KI-gestützte Optimierung von Geschäftsprozessen',
    // SEO Meta Descriptions
    'meta.home.description': 'Hören Sie auf, Zeit mit wiederholenden Aufgaben zu verschwenden. Espai.ai zeichnet Ihre Prozesse auf, findet Ineffizienzen mit KI und erstellt Automatisierungen, die mehr als 20 Stunden pro Woche sparen. Zahlen Sie nur, wenn Sie anfangen zu sparen.',
    'meta.about.description': 'Espai.ai hilft Unternehmen dabei, manuelle Arbeit durch intelligente Prozessautomatisierung zu eliminieren. Wir haben Unternehmen geholfen, 40% der Mitarbeiterzeit zu sparen und Betriebskosten um 30% zu reduzieren.',
    'meta.pricing.description': 'Transparente Preise: €70-100 pro Gerät pro Monat. Sie zahlen nur, nachdem Automatisierungen anfangen, Ihnen Zeit zu sparen. Die meisten Unternehmen sehen ROI innerhalb von 30 Tagen.',
    'meta.faq.description': 'Erhalten Sie Antworten zur KI-Automatisierungsplattform von Espai.ai. Erfahren Sie, wie unsere Prozessaufzeichnung und -analyse Ihrem Unternehmen mehr als 20 Stunden pro Woche sparen kann.',
    'meta.contact.description': 'Bereit, mehr als 20 Stunden pro Woche zu sparen? Kontaktieren Sie Espai.ai für eine kostenlose Prozessanalyse. Sehen Sie, wie KI-Automatisierung Ihre Geschäftsabläufe transformieren kann.',
    'meta.privacy.description': 'Datenschutzerklärung und Datenschutzpraxis von Espai.ai. Erfahren Sie, wie wir Ihre Geschäftedaten in unserer KI-Prozessautomatisierungsplattform sichern.',
    'nav.home': 'Startseite',
    'nav.about': 'Über uns',
    'nav.pricing': 'Preise',
    'nav.faq': 'FAQ',
    'nav.contact': 'Kontakt',
    'nav.resources': 'Ressourcen',
    'nav.privacy': 'Datenschutzerklärung',
    'hero.title': 'Sparen Sie mehr als 20 Stunden pro Woche mit KI-Automatisierung',
    'hero.subtitle': 'Hören Sie auf, Zeit mit wiederholenden Aufgaben zu verschwenden. Unsere KI zeichnet Ihre Prozesse auf, findet Ineffizienzen und erstellt Automatisierungen, die wirklich funktionieren.',
    'hero.cta': 'Kostenlose Analyse starten',
    'hero.cta.secondary': 'So funktioniert es',
    'footer.rights': 'Alle Rechte vorbehalten.',
    'footer.crafted': 'gemacht mit ♡ in barcelona',
    // Contact form translations
    'contact.title': 'Erhalten Sie Ihre kostenlose Prozessanalyse',
    'contact.subtitle': 'Sehen Sie, wie viel Zeit Ihr Unternehmen mit KI-Automatisierung sparen kann',
    'contact.form.name': 'Vollständiger Name',
    'contact.form.email': 'E-Mail-Adresse',
    'contact.form.company': 'Firmenname',
    'contact.form.phone': 'Telefonnummer',
    'contact.form.employees': 'Anzahl der Mitarbeiter',
    'contact.form.employees.option1': '1-10 Mitarbeiter',
    'contact.form.employees.option2': '11-50 Mitarbeiter',
    'contact.form.employees.option3': '51-200 Mitarbeiter',
    'contact.form.employees.option4': '200+ Mitarbeiter',
    'contact.form.interest': 'Ich bin interessiert an',
    'contact.form.interest.demo': 'Kostenlose Prozessanalyse',
    'contact.form.interest.pricing': 'Preisinformationen',
    'contact.form.interest.other': 'Andere',
    'contact.form.message': 'Erzählen Sie uns von Ihren aktuellen Prozessen und Problemen',
    'contact.form.submit': 'Kostenlose Analyse erhalten',
    'contact.form.sending': 'Wird gesendet...',
    'contact.form.success': 'Nachricht erfolgreich gesendet! Wir werden uns innerhalb von 24 Stunden bei Ihnen melden, um Ihre kostenlose Analyse zu planen.',
    'contact.form.error': 'Fehler beim Senden der Nachricht. Bitte versuchen Sie es erneut oder kontaktieren Sie uns direkt.',
    'contact.form.required': 'Dieses Feld ist erforderlich',
    // Language detection translations
    'lang.detection.title': 'Spracheinstellung',
    'lang.detection.message': 'Wir haben erkannt, dass Ihr Browser auf {language} eingestellt ist. Möchten Sie zu dieser Sprache wechseln?',
    'lang.detection.switch': 'Zu {language} wechseln',
    'lang.detection.stay': 'Bei Englisch bleiben',
    'lang.detection.dismiss': 'Nicht mehr fragen'
  }
};
